---
title: "Lab_assignment_1"
author: "Ivan"
date: "10/30/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 1.
## Read data
```{r}
markov100 <- read.delim("~/Desktop/MSIA/Courses/MSIA 400 Everything starts with data/Lab Assignment 1/markov100.txt", header=FALSE)
```
## (a)
```{r}
library(expm)
a = rep(0,100)
a[1]= 1
p = a %*%(as.matrix(markov100) %^% 10)
p[5]
```

##(b)

```{r}
b = rep(0,100)
b[1:3]=1/3
p_b = b %*%(as.matrix(markov100) %^% 10)
p_b[10]
```

##(c)
```{r}
Q <- t(as.matrix(markov100))-diag(100)
Q[100,]<-rep(1,100)
rhs = c(rep(0,99),1)
pi = solve(Q)%*%rhs
pi[1]
```

##(d)
```{r}
b = as.matrix(markov100)[-100,-100]
Q = diag(99)-b
e = rep(1,99)
m = solve(Q) %*% e
m[1]
```

# 2.

## read data
```{r}
web <- read.delim("~/Desktop/MSIA/Courses/MSIA 400 Everything starts with data/Lab Assignment 1/webtraffic.txt")

```
## (a)
```{r}
traffic <- matrix(colSums(web),nrow = 9,byrow = T)
traffic

```
##(b)
```{r}
traffic[9,1]<-1000
p <- traffic/colSums(traffic)
p
```
## (c)
```{r}
Q <- t(p)-diag(9)
Q[9,]<-rep(1,9)
rhs = c(rep(0,8),1)
pi = solve(Q)%*%rhs
pi
```

##(d)
```{r}
w <- c(0.1,2,3,5,5,3,3,2)
B = p[-9,-9]
Q = diag(8)-B
e = rep(1,8)
m = solve(Q) %*% e
avg_time = w %*% pi[-9]
# average time
m[1,1] * avg_time
```

##(e)
```{r}
traffic[2,6] = 0.3*traffic[2,3]
traffic[2,3] = 0.7*traffic[2,3]
traffic[2,7] = 0.2*traffic[2,4]
traffic[2,4] = 0.8*traffic[2,3]

p <- traffic/colSums(traffic)
Q <- t(p)-diag(9)
Q[9,]<-rep(1,9)
rhs = c(rep(0,8),1)
pi_2 = solve(Q)%*%rhs
pi_2

var(pi)
var(pi_2)
```

variance decreased means links did balance the traffic. 